---
application:
  name: "doxat"
  project: "doxat"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "doxat"
  version: "12"
routers:
- name: "main-doxat"
  routes:
  - application_name: "doxat"
    paths:
    - "/*"
